version: '2'
services:
  app:
    build:
      context: .
      args:
        - SQL_DB_URI=${SQL_DB_URI}
    ports:
    - "5000:5000"
    container_name: py_webauthn
    env_file: .env
    user: nobody
    volumes:
        - ./webauthn:/app/webauthn:ro
        - ./flask_demo:/app/flask_demo:ro
